//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebUI.RegulationServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PortalLinkConfig", Namespace="http://schemas.datacontract.org/2004/07/WebUI.Areas.Regulation.Helpers")]
    [System.SerializableAttribute()]
    public partial class PortalLinkConfig : WebUI.RegulationServiceReference.LinkConfig {
        
        private WebUI.RegulationServiceReference.LinkGroup LinkGroupk__BackingFieldField;
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<LinkGroup>k__BackingField", IsRequired=true)]
        public WebUI.RegulationServiceReference.LinkGroup LinkGroupk__BackingField {
            get {
                return this.LinkGroupk__BackingFieldField;
            }
            set {
                if ((this.LinkGroupk__BackingFieldField.Equals(value) != true)) {
                    this.LinkGroupk__BackingFieldField = value;
                    this.RaisePropertyChanged("LinkGroupk__BackingField");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseObject", Namespace="http://schemas.datacontract.org/2004/07/Base")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebUI.RegulationServiceReference.FileData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebUI.RegulationServiceReference.LinkConfig))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebUI.RegulationServiceReference.PortalLinkConfig))]
    public partial class BaseObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HiddenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SortOrderField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Hidden {
            get {
                return this.HiddenField;
            }
            set {
                if ((this.HiddenField.Equals(value) != true)) {
                    this.HiddenField = value;
                    this.RaisePropertyChanged("Hidden");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SortOrder {
            get {
                return this.SortOrderField;
            }
            set {
                if ((this.SortOrderField.Equals(value) != true)) {
                    this.SortOrderField = value;
                    this.RaisePropertyChanged("SortOrder");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FileData", Namespace="http://schemas.datacontract.org/2004/07/Base")]
    [System.SerializableAttribute()]
    public partial class FileData : WebUI.RegulationServiceReference.BaseObject {
        
        private System.DateTime ChangeDatek__BackingFieldField;
        
        private System.DateTime CreationDatek__BackingFieldField;
        
        private System.Guid FileIDk__BackingFieldField;
        
        private string FileNamek__BackingFieldField;
        
        private System.Guid Keyk__BackingFieldField;
        
        private long Sizek__BackingFieldField;
        
        private int Statek__BackingFieldField;
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ChangeDate>k__BackingField", IsRequired=true)]
        public System.DateTime ChangeDatek__BackingField {
            get {
                return this.ChangeDatek__BackingFieldField;
            }
            set {
                if ((this.ChangeDatek__BackingFieldField.Equals(value) != true)) {
                    this.ChangeDatek__BackingFieldField = value;
                    this.RaisePropertyChanged("ChangeDatek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<CreationDate>k__BackingField", IsRequired=true)]
        public System.DateTime CreationDatek__BackingField {
            get {
                return this.CreationDatek__BackingFieldField;
            }
            set {
                if ((this.CreationDatek__BackingFieldField.Equals(value) != true)) {
                    this.CreationDatek__BackingFieldField = value;
                    this.RaisePropertyChanged("CreationDatek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<FileID>k__BackingField", IsRequired=true)]
        public System.Guid FileIDk__BackingField {
            get {
                return this.FileIDk__BackingFieldField;
            }
            set {
                if ((this.FileIDk__BackingFieldField.Equals(value) != true)) {
                    this.FileIDk__BackingFieldField = value;
                    this.RaisePropertyChanged("FileIDk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<FileName>k__BackingField", IsRequired=true)]
        public string FileNamek__BackingField {
            get {
                return this.FileNamek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.FileNamek__BackingFieldField, value) != true)) {
                    this.FileNamek__BackingFieldField = value;
                    this.RaisePropertyChanged("FileNamek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Key>k__BackingField", IsRequired=true)]
        public System.Guid Keyk__BackingField {
            get {
                return this.Keyk__BackingFieldField;
            }
            set {
                if ((this.Keyk__BackingFieldField.Equals(value) != true)) {
                    this.Keyk__BackingFieldField = value;
                    this.RaisePropertyChanged("Keyk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Size>k__BackingField", IsRequired=true)]
        public long Sizek__BackingField {
            get {
                return this.Sizek__BackingFieldField;
            }
            set {
                if ((this.Sizek__BackingFieldField.Equals(value) != true)) {
                    this.Sizek__BackingFieldField = value;
                    this.RaisePropertyChanged("Sizek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<State>k__BackingField", IsRequired=true)]
        public int Statek__BackingField {
            get {
                return this.Statek__BackingFieldField;
            }
            set {
                if ((this.Statek__BackingFieldField.Equals(value) != true)) {
                    this.Statek__BackingFieldField = value;
                    this.RaisePropertyChanged("Statek__BackingField");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LinkConfig", Namespace="http://schemas.datacontract.org/2004/07/WebUI.Areas.Regulation.Helpers")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebUI.RegulationServiceReference.PortalLinkConfig))]
    public partial class LinkConfig : WebUI.RegulationServiceReference.BaseObject {
        
        private WebUI.RegulationServiceReference.FileData Imagek__BackingFieldField;
        
        private string Linkk__BackingFieldField;
        
        private string Titlek__BackingFieldField;
        
        private WebUI.RegulationServiceReference.Random randomField;
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Image>k__BackingField", IsRequired=true)]
        public WebUI.RegulationServiceReference.FileData Imagek__BackingField {
            get {
                return this.Imagek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Imagek__BackingFieldField, value) != true)) {
                    this.Imagek__BackingFieldField = value;
                    this.RaisePropertyChanged("Imagek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Link>k__BackingField", IsRequired=true)]
        public string Linkk__BackingField {
            get {
                return this.Linkk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Linkk__BackingFieldField, value) != true)) {
                    this.Linkk__BackingFieldField = value;
                    this.RaisePropertyChanged("Linkk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Title>k__BackingField", IsRequired=true)]
        public string Titlek__BackingField {
            get {
                return this.Titlek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Titlek__BackingFieldField, value) != true)) {
                    this.Titlek__BackingFieldField = value;
                    this.RaisePropertyChanged("Titlek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public WebUI.RegulationServiceReference.Random random {
            get {
                return this.randomField;
            }
            set {
                if ((object.ReferenceEquals(this.randomField, value) != true)) {
                    this.randomField = value;
                    this.RaisePropertyChanged("random");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Random", Namespace="http://schemas.datacontract.org/2004/07/System")]
    [System.SerializableAttribute()]
    public partial class Random : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int[] SeedArrayField;
        
        private int inextField;
        
        private int inextpField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int[] SeedArray {
            get {
                return this.SeedArrayField;
            }
            set {
                if ((object.ReferenceEquals(this.SeedArrayField, value) != true)) {
                    this.SeedArrayField = value;
                    this.RaisePropertyChanged("SeedArray");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int inext {
            get {
                return this.inextField;
            }
            set {
                if ((this.inextField.Equals(value) != true)) {
                    this.inextField = value;
                    this.RaisePropertyChanged("inext");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int inextp {
            get {
                return this.inextpField;
            }
            set {
                if ((this.inextpField.Equals(value) != true)) {
                    this.inextpField = value;
                    this.RaisePropertyChanged("inextp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LinkGroup", Namespace="http://schemas.datacontract.org/2004/07/WebUI.Areas.Regulation.Helpers")]
    public enum LinkGroup : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RegionORVPortal = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OtherPortal = 50,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RegulationServiceReference.IRegulationService")]
    public interface IRegulationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegulationService/PortlaLinks", ReplyAction="http://tempuri.org/IRegulationService/PortlaLinksResponse")]
        WebUI.RegulationServiceReference.PortalLinkConfig[] PortlaLinks();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegulationService/PortlaLinks", ReplyAction="http://tempuri.org/IRegulationService/PortlaLinksResponse")]
        System.Threading.Tasks.Task<WebUI.RegulationServiceReference.PortalLinkConfig[]> PortlaLinksAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRegulationServiceChannel : global::WebUI.RegulationServiceReference.IRegulationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RegulationServiceClient : System.ServiceModel.ClientBase<global::WebUI.RegulationServiceReference.IRegulationService>, global::WebUI.RegulationServiceReference.IRegulationService {
        
        public RegulationServiceClient() {
        }
        
        public RegulationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RegulationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegulationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegulationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebUI.RegulationServiceReference.PortalLinkConfig[] PortlaLinks() {
            return base.Channel.PortlaLinks();
        }
        
        public System.Threading.Tasks.Task<WebUI.RegulationServiceReference.PortalLinkConfig[]> PortlaLinksAsync() {
            return base.Channel.PortlaLinksAsync();
        }
    }
}
